const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("irSystem", {
  getBootstrap: () => ipcRenderer.invoke("platform:bootstrap"),
  getModuleData: (moduleId) => ipcRenderer.invoke("platform:module-data", moduleId),
  probeProvider: (providerId) => ipcRenderer.invoke("platform:provider-probe", providerId),
  selectProvider: (providerId) => ipcRenderer.invoke("platform:select-provider", providerId),
  saveProviderConfig: (input) => ipcRenderer.invoke("platform:provider-config", input),
  archiveRequest: (action, params) => ipcRenderer.invoke("archive:request", action, params),
  derivativesRequest: (action, params) => ipcRenderer.invoke("derivatives:request", action, params),
  revealArchiveAsset: (id) => ipcRenderer.invoke("archive:reveal", id),
  syncGetState: () => ipcRenderer.invoke("sync:state"),
  syncCheckLocal: (force=false) => ipcRenderer.invoke('sync:check-local',force),
  syncPermissionHelp: action => ipcRenderer.invoke('sync:permission-help',action),
  syncWebLogin: () => ipcRenderer.invoke('sync:web-login'),
  syncProbeIma: (selection={}) => ipcRenderer.invoke('sync:probe-ima',selection),
  syncPreflightPrompt: provider => ipcRenderer.invoke('sync:preflight-prompt',provider),
  syncSetIssueConsidered: input => ipcRenderer.invoke('sync:issue-considered',input),
  syncSaveSettings: (input) => ipcRenderer.invoke("sync:settings", input),
  syncSaveConsoleSettings: (input) => ipcRenderer.invoke("sync:console-settings", input),
  syncProbePi: () => ipcRenderer.invoke("sync:probe-pi"),
  syncPrompt: (provider,kind,range) => ipcRenderer.invoke('sync:prompt',provider,kind,range),
  copyText: text => ipcRenderer.invoke('platform:copy-text',text),
  terminalList: () => ipcRenderer.invoke('terminal:list'),
  terminalSnapshot: id => ipcRenderer.invoke('terminal:snapshot',id),
  terminalCreate: input => ipcRenderer.invoke('terminal:create',input),
  terminalInput: (id,data) => ipcRenderer.invoke('terminal:input',id,data),
  terminalResize: (id,cols,rows) => ipcRenderer.invoke('terminal:resize',id,cols,rows),
  terminalRename: (id,title) => ipcRenderer.invoke('terminal:rename',id,title),
  terminalClose: id => ipcRenderer.invoke('terminal:close',id),
  terminalChooseDirectory: () => ipcRenderer.invoke('terminal:choose-directory'),
  onTerminalEvent: callback => {const listener=(_event,payload)=>callback(payload);ipcRenderer.on('terminal:event',listener);return ()=>ipcRenderer.removeListener('terminal:event',listener);},
  syncScan: (providers) => ipcRenderer.invoke("sync:scan", providers),
  syncApprove: (kind, resumeId, selection) => ipcRenderer.invoke("sync:approve", kind, resumeId, selection),
  syncStop: (id) => ipcRenderer.invoke("sync:stop", id),
  syncExplain: (id) => ipcRenderer.invoke("sync:explain", id),
});
